name: shivam_portfolio
description: "My flutter portfolio app"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  supabase_flutter: ^2.8.4
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  device_frame: ^1.2.0
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.4.1
  mouse_follower: ^1.3.7
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_custom_clippers: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500